services:
  app:
    build: .
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - node_modules/
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "preview"]
    restart: always
